import type {
	IAuthenticateGeneric,
	Icon,
	ICredentialTestRequest,
	ICredentialType,
	INodeProperties,
} from 'n8n-workflow';

export class JobAvailabilityApi implements ICredentialType {
	name = 'jobAvailabilityApi';

	displayName = 'Job Availability API';

	icon: Icon = {
		light: 'file:jobAvailabilityApi.svg',
		dark: 'file:jobAvailabilityApi.dark.svg',
	};

	documentationUrl =
		'https://github.com/orbruno/n8n-nodes-job-availability#configure-credentials';

	supportedNodes = ['jobAvailability'];

	restrictToSupportedNodes = true as const;

	properties: INodeProperties[] = [
		{
			displayName: 'Base URL',
			name: 'baseUrl',
			type: 'string',
			required: true,
			default: 'http://127.0.0.1:5002',
			placeholder: 'http://host.docker.internal:5002',
			validateType: 'url',
			description:
				'Root URL of the self-hosted service, without a trailing slash or embedded credentials',
		},
		{
			displayName: 'Service Token',
			name: 'serviceToken',
			type: 'string',
			typeOptions: { password: true },
			required: true,
			default: '',
			description: 'Operator token generated by the local service and shown only once',
		},
	];

	authenticate: IAuthenticateGeneric = {
		type: 'generic',
		properties: {
			headers: {
				Authorization: '=Bearer {{$credentials.serviceToken}}',
			},
		},
	};

	test: ICredentialTestRequest = {
		request: {
			baseURL:
				'={{$credentials.baseUrl.endsWith("/") ? $credentials.baseUrl.slice(0, -1) : $credentials.baseUrl}}',
			url: '/v1/credentials/test',
			method: 'GET',
		},
	};
}
